-- =======================================================
-- ESQUEMA DE BASE DE DATOS Y STORAGE PARA SUPABASE
-- (Catálogo Global, Descarga con Sesión y Rol de Usuario Padre)
-- Copia y pega este script en el SQL Editor de tu proyecto Supabase
-- =======================================================

-- 1. Tabla de administradores (Usuarios Padre)
create table if not exists public.admins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade unique,
  email text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS en la tabla admins
alter table public.admins enable row level security;

-- Permitir a usuarios autenticados consultar la tabla admins para verificar su propio rol
drop policy if exists "Lectura de admins para usuarios autenticados" on public.admins;
create policy "Lectura de admins para usuarios autenticados" 
  on public.admins for select 
  using (auth.role() = 'authenticated');

-- 2. Función auxiliar segura para verificar si el usuario actual es Admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.admins 
    where user_id = auth.uid()
  );
end;
$$ language plpgsql security definer;

-- 3. Tabla canciones y columnas de autoría
create table if not exists public.canciones (
  id bigint generated by default as identity primary key,
  titulo text not null,
  artista text not null,
  "tipoArchivo" text not null check ("tipoArchivo" in ('pdf', 'word')),
  "archivoUrl" text not null,
  user_id uuid references auth.users(id) on delete cascade,
  user_email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Asegurar que las columnas existan si la tabla ya estaba creada previamente
alter table public.canciones 
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists user_email text;

-- Habilitar RLS en canciones
alter table public.canciones enable row level security;

-- POLÍTICA 1: LECTURA PÚBLICA (Todos ven y buscan todas las canciones)
drop policy if exists "Permitir lectura publica de canciones" on public.canciones;
create policy "Permitir lectura publica de canciones" 
  on public.canciones for select 
  using (true);

-- POLÍTICA 2: SUBIDA (Cualquier usuario autenticado puede subir canciones)
drop policy if exists "Permitir subida publica de canciones" on public.canciones;
drop policy if exists "Permitir subida a usuarios autenticados" on public.canciones;
create policy "Permitir subida a usuarios autenticados" 
  on public.canciones for insert 
  with check (auth.uid() is not null);

-- POLÍTICA 3: ELIMINACIÓN (EXCLUSIVA para el Usuario Padre / Admin)
drop policy if exists "Permitir eliminacion solo al dueno" on public.canciones;
drop policy if exists "Permitir eliminacion solo a usuario padre" on public.canciones;
create policy "Permitir eliminacion solo a usuario padre" 
  on public.canciones for delete 
  using (public.is_admin());

-- 4. POLÍTICAS DE STORAGE (Bucket 'archivos')
-- Subida: Usuarios autenticados
drop policy if exists "Permitir subida publica en bucket archivos" on storage.objects;
drop policy if exists "Permitir subida a autenticados en bucket archivos" on storage.objects;
create policy "Permitir subida a autenticados en bucket archivos"
  on storage.objects for insert
  with check (bucket_id = 'archivos' and auth.role() = 'authenticated');

-- Lectura: Pública para iframes
drop policy if exists "Permitir lectura publica en bucket archivos" on storage.objects;
create policy "Permitir lectura publica en bucket archivos"
  on storage.objects for select
  using (bucket_id = 'archivos');

-- Eliminación: EXCLUSIVA para el Usuario Padre
drop policy if exists "Permitir eliminacion a autenticados en storage" on storage.objects;
drop policy if exists "Permitir eliminacion solo a usuario padre en storage" on storage.objects;
create policy "Permitir eliminacion solo a usuario padre en storage"
  on storage.objects for delete
  using (bucket_id = 'archivos' and public.is_admin());

-- =======================================================
-- CÓMO ASIGNAR AL USUARIO PADRE:
-- Una vez registrado tu usuario en la app, puedes asignarle el rol de Admin
-- ejecutando esta consulta (reemplaza 'tu-correo@gmail.com' con tu correo real):
--
-- insert into public.admins (user_id, email)
-- select id, email from auth.users where email = 'tu-correo@gmail.com'
-- on conflict (user_id) do nothing;
-- =======================================================
