-- =======================================================
-- ESQUEMA DE BASE DE DATOS Y STORAGE PARA SUPABASE
-- Copia y pega este script en el SQL Editor de tu proyecto Supabase
-- =======================================================

-- 1. Crear tabla de canciones
create table if not exists public.canciones (
  id bigint generated by default as identity primary key,
  titulo text not null,
  artista text not null,
  "tipoArchivo" text not null check ("tipoArchivo" in ('pdf', 'word')),
  "archivoUrl" text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar Seguridad por Fila (Row Level Security - RLS) en la tabla canciones
alter table public.canciones enable row level security;

-- 3. Políticas de acceso para la tabla canciones
drop policy if exists "Permitir lectura publica de canciones" on public.canciones;
create policy "Permitir lectura publica de canciones" 
  on public.canciones 
  for select 
  using (true);

drop policy if exists "Permitir subida publica de canciones" on public.canciones;
create policy "Permitir subida publica de canciones" 
  on public.canciones 
  for insert 
  with check (true);

-- 4. Políticas de Seguridad para Storage (Permitir subir archivos al bucket 'archivos')
drop policy if exists "Permitir subida publica en bucket archivos" on storage.objects;
create policy "Permitir subida publica en bucket archivos"
  on storage.objects for insert
  with check (bucket_id = 'archivos');

drop policy if exists "Permitir lectura publica en bucket archivos" on storage.objects;
create policy "Permitir lectura publica en bucket archivos"
  on storage.objects for select
  using (bucket_id = 'archivos');

drop policy if exists "Permitir actualizacion publica en bucket archivos" on storage.objects;
create policy "Permitir actualizacion publica en bucket archivos"
  on storage.objects for update
  using (bucket_id = 'archivos');

-- =======================================================
-- RECORDATORIO IMPORTANTE PARA STORAGE:
-- Asegúrate de que creaste el bucket con nombre exacto: archivos
-- y que activaste la casilla "Public bucket".
-- =======================================================
